# Generated by Django 3.2.25 on 2024-05-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ststats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='data',
            field=models.JSONField(),
        ),
    ]
