# Generated by Django 3.2.25 on 2024-05-31 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ststats', '0003_run_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_creation_date', models.DateTimeField()),
                ('display_name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='run',
            name='player_id',
        ),
        migrations.AddField(
            model_name='run',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ststats.player'),
            preserve_default=False,
        ),
    ]
