# Generated by Django 3.2.25 on 2024-05-31 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ststats', '0004_auto_20240531_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='player',
            new_name='player_id',
        ),
    ]
